/** This is an autogenerated file, please do not change this file directly. */
declare namespace AnalyzeDataModuleScssModule {
  export interface IAnalyzeDataModuleScss {
    darkGray: string;
    datasetsContainer: string;
    fadeIn: string;
    singleDataset: string;
    title: string;
  }
}

declare const AnalyzeDataModuleScssModule: AnalyzeDataModuleScssModule.IAnalyzeDataModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AnalyzeDataModuleScssModule.IAnalyzeDataModuleScss;
};

export = AnalyzeDataModuleScssModule;
