/** This is an autogenerated file, please do not change this file directly. */
declare namespace ChartSingleDatasetModuleScssModule {
  export interface IChartSingleDatasetModuleScss {
    resetDataset: string;
  }
}

declare const ChartSingleDatasetModuleScssModule: ChartSingleDatasetModuleScssModule.IChartSingleDatasetModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ChartSingleDatasetModuleScssModule.IChartSingleDatasetModuleScss;
};

export = ChartSingleDatasetModuleScssModule;
