/** This is an autogenerated file, please do not change this file directly. */
declare namespace LookingGlassModuleScssModule {
  export interface ILookingGlassModuleScss {
    darkGray: string;
    draggableBar: string;
    fadeIn: string;
    lookingGlassApp: string;
  }
}

declare const LookingGlassModuleScssModule: LookingGlassModuleScssModule.ILookingGlassModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LookingGlassModuleScssModule.ILookingGlassModuleScss;
};

export = LookingGlassModuleScssModule;
