pull_request_rules:
  - name: Automatic merge on CI completion
    conditions:
      - label=["merge-when-ready"]
      - status_success=dry-distribution
    actions:
      merge:
        method: merge
  - name: Delete branch when merged
    conditions:
      - merged
    actions:
      delete_head_branch:
        force: false
