/** This is an autogenerated file, please do not change this file directly. */
declare namespace HomeBarModuleScssModule {
  export interface IHomeBarModuleScss {
    darkGray: string;
    fadeIn: string;
    homeBar: string;
    routeOption: string;
    selected: string;
  }
}

declare const HomeBarModuleScssModule: HomeBarModuleScssModule.IHomeBarModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HomeBarModuleScssModule.IHomeBarModuleScss;
};

export = HomeBarModuleScssModule;
