# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    setup:
        docker:
            - image: circleci/node:10.18.0
        steps:
            - checkout
            - run:
                - name: Install dependencies
                - command: yarn
workflows:
    version: 2
    build_and_lint:
        jobs:
            - setup
