/** This is an autogenerated file, please do not change this file directly. */
declare namespace MergeDatasetsDialogModuleScssModule {
  export interface IMergeDatasetsDialogModuleScss {
    dataset: string;
    datasetContainer: string;
    selectDatasetsTitle: string;
    selectedDataset: string;
  }
}

declare const MergeDatasetsDialogModuleScssModule: MergeDatasetsDialogModuleScssModule.IMergeDatasetsDialogModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MergeDatasetsDialogModuleScssModule.IMergeDatasetsDialogModuleScss;
};

export = MergeDatasetsDialogModuleScssModule;
