/** This is an autogenerated file, please do not change this file directly. */
declare namespace HomeModuleScssModule {
  export interface IHomeModuleScss {
    darkGray: string;
    description: string;
    header: string;
    homePage: string;
  }
}

declare const HomeModuleScssModule: HomeModuleScssModule.IHomeModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HomeModuleScssModule.IHomeModuleScss;
};

export = HomeModuleScssModule;
