/** Declaration file generated by dts-gen */
declare module "speedtest-net" {
  export = speedtest_net;

  function speedtest_net(options: any): any;

  namespace speedtest_net {
    const prototype: {};

    function visual(options: any, callback: any): any;

    namespace visual {
      const prototype: {};
    }
  }
}
