/** This is an autogenerated file, please do not change this file directly. */
declare namespace SingleDatasetModuleScssModule {
  export interface ISingleDatasetModuleScss {
    darkGray: string;
    datasetNonIdeal: string;
    fadeIn: string;
    jsonContainer: string;
    jsonContainerLabel: string;
    metadataContainer: string;
    metadataContainerLabel: string;
    metadataTitle: string;
    metadataValue: string;
  }
}

declare const SingleDatasetModuleScssModule: SingleDatasetModuleScssModule.ISingleDatasetModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SingleDatasetModuleScssModule.ISingleDatasetModuleScss;
};

export = SingleDatasetModuleScssModule;
